name: resource_reaper
description: A lightweight resource manager for Dart and Flutter applications that handles the lifecycle and disposal of resources. Helps prevent memory leaks when caching data.
version: 1.0.4
repository: https://github.com/DevXpressInc/resource_reaper
issue_tracker: https://github.com/DevXpressInc/resource_reaper/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  clock: ^1.0.0

dev_dependencies:
  fake_async: ^1.3.3
  lints: ^5.0.0
  test: ^1.24.0
