name: resource_reaper
description: A resource manager for Dart and Flutter
version: 1.0.0
repository: https://github.com/DevXpressInc/resource_reaper
issue_tracker: https://github.com/DevXpressInc/resource_reaper/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  clock: ^1.1.2

dev_dependencies:
  fake_async: ^1.3.3
  lints: ^5.0.0
  test: ^1.24.0
