name: riverpod_usage
description: A complex example for usage with riverpod
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.6.2

dependencies:
  resource_reaper:
    path: ../../
  riverpod: ^2.6.1

dev_dependencies:
  lints: ^5.0.0
